apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-mc1-subscription
  namespace: istio-apps
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/github-path: bookinfo-mc1
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: istio-apps/istio-bookinfo-channel
  placement:
    local: false
    clusters:
    - name: mcsmcstest1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-mc2-subscription
  namespace: istio-apps
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/github-path: bookinfo-mc2
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: istio-apps/istio-bookinfo-channel
  placement:
    local: false
    clusters:
    - name: mcsmcstest2
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-gateway-subscription
  namespace: istio-apps
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/github-path: bookinfo-gateway
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: istio-apps/istio-bookinfo-channel
  placement:
    local: true
