apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: tcp-echo
  namespace: istio-apps-testing
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - tcp-echo
